### ISSUE TITLE
Does the `targetReplicas` field have to be `int`? 

### ISSUE THREAD

**Issue by fighterhit** [tkestack/cron-hpa#3]
Does the `targetReplicas` field have to be `int`?  When I use `kubectl edit` to change to string, the program reported the following error:
```
I0901 14:11:08.611624   59983 controller.go:127] Starting sync all
E0901 14:11:08.614314   59983 controller.go:130] Failed to list cronhpas
I0901 14:11:18.614515   59983 controller.go:127] Starting sync all
E0901 14:11:18.617316   59983 controller.go:130] Failed to list cronhpas
I0901 14:11:28.617551   59983 controller.go:127] Starting sync all
E0901 14:11:28.620291   59983 controller.go:130] Failed to list cronhpas
I0901 14:11:31.965057   59983 discovery.go:215] Invalidating discovery information
I0901 14:11:38.620585   59983 controller.go:127] Starting sync all
E0901 14:11:38.623234   59983 controller.go:130] Failed to list cronhpas
I0901 14:11:48.623463   59983 controller.go:127] Starting sync all
E0901 14:11:48.626451   59983 controller.go:130] Failed to list cronhpas
I0901 14:11:58.626677   59983 controller.go:127] Starting sync all
E0901 14:11:58.629486   59983 controller.go:130] Failed to list cronhpas
I0901 14:12:01.965352   59983 discovery.go:215] Invalidating discovery information
```

**Comment by fighterhit** [comment]
In addition, because of concerns about possible failure in the production environment, is there any way to  judge or track the status of CronHPA? I see the `status` field only have the `lastScheduleTime`. Thanks.

**Comment by hex108** [comment]
> Does the targetReplicas field have to be int?

Yes, what other type do you want to support?

> In addition, because of concerns about possible failure in the production environment, is there any way to judge or track the status of CronHPA?

Get the latest repliaces value of the app and compare with it? Howerver it will be better to add more status in `CronHPA`.
